insert into DPT_STATUS_DESCRIPTION (STATUS_CODE, LANGUAGE_CODE, DESCRIPTION) values (1,1,'Success');
insert into DPT_STATUS_DESCRIPTION (STATUS_CODE, LANGUAGE_CODE, DESCRIPTION) values (1,2,'הצלחה');
commit;